version: '3.8'
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
  api:
    container_name: api-container
    restart: always
    build: ./server
    ports: 
      - "5000:5000"
    depends_on: 
      - mongo
  client:
    container_name: client-container
    restart: always
    build: ./client
    ports: 
      - "8080:8080"
    depends_on: 
      - api
  mongo:
    container_name: mongo-backend
    image: mongo
    expose: 
      - "27017"
    ports: 
      - "27017:27017"
    volumes: 
      - apiDB:/data/db

volumes: 
  apiDB: